services:
  postgres:
    image: postgres:17
    ports:
      - "8322:5432"
    environment:
      POSTGRES_USER: cludbox
      POSTGRES_PASSWORD: cludbox
      POSTGRES_DB: cludbox
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
